### PR TITLE
build(stark-all): fix issues with `describe()`, `it()`, `beforeEach()`, etc. in stark-ui and stark-core

### PR DESCRIPTION
**Pull request by SuperITMan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

IntelliJ complains all the time in `spec.ts` files in `stark-ui` and `stark-core` about `describe()`, `it()`, `beforeEach()`, etc.

This is due to the fact that the `stark-testing` dependencies are installed thanks to symlinks.

## What is the new behavior?

There is no npm symlinks between `stark-testing` and the other packages (`stark-core` & `stark-ui`).
It is unfortunately not yet perfect since we need to repeat those 2 deps: 
  * "@types/jasmine": "^3.3.12",
  * "@types/node": "^8.10.37"

in `stark-testing` (dependencies) and in `stark-core` and `stark-ui` (devDependencies).

Also, we have now a strong link between stark-ui and stark-testing and between stark-core and stark-testing since they use `karma` directly from `"../stark-testing/node_modules/karma/bin/karma"`

Nevertheless, thanks to that, IntelliJ handles correctly `describe()`, `it()`, `beforeEach()`, etc. in our spec files 😊 
And it works really well so we don't have anymore any suggestion to import those methods from `@angular/core/testing/src/testing_internal` 😃 

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

### CODE REVIEW

**Comment by cnomes** [comment]
When I try to `clean:slate` the branch my build fails at several places.
```bash
===> build.sh tsc -p packages/tsconfig.json ==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==>==
packages/stark-core/src/modules/logging/services/logging.service.spec.ts:100:10 - error TS2322: Type 'Action' is not assignable to type 'StarkLogMessageAction'.
  Property 'message' is missing in type 'Action'.

100             const dispatchedAction: StarkLogMessageAction = mockStore.dispatch.calls.mostRecent().args[0];
                      ~~~~~~~~~~~~~~~~


```

**Comment by SuperITMan** [comment]
@cnomes That's weird 😕 
I take a look on it

**Comment by SuperITMan** [comment]
Actually I think it's due to an update of tslint... I'll have to fix those issues in the code.

**Comment by christophercr** [comment]
It's indeed an issue about typings.... More specifically @types/jasmine....
I'm looking at those and fixing them ;)

**Comment by christophercr** [comment]
The issues about `@types/jasmine` has been solved in #1212 👍

**Comment by SuperITMan** [comment]
I think that my PR is fine now 😊

**Pull request merged**
