### PR TITLE
Feature/docs stark-rbac testing subpackage

### PR DESCRIPTION
**Pull request by christophercr**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1600 

## What is the new behavior?
The docs of the testing subpackage from the Stark-RBAC are now generated and included in the Stark API Docs.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information
Took the chance to do some minor fixes/corrections to the existing documentation 👍

### CODE REVIEW

**Comment by christophercr** [comment]
Mmm, then... would we need to duplicate the same "usage" docs for every mock class?
And should we remove the "usage" section from `TESTING_SUBPACKAGE.md`?

**Comment by SuperITMan** [comment]
I think it would be easier to understand the usage of the mocked classes...
Indeed, removing the examples from the TESTING_SUBPACKAGES.md. The file could contain only this:

```markdown
# Stark RBAC Testing subpackage

> @nationalbankbelgium/stark-rbac/testing

Subpackage of Stark RBAC that contains the mock classes that come in hand when implementing unit tests that depend on
any of the main services provided by Stark RBAC.

## Mock Classes

The mock classes provided by this subpackage are the following:

-   [MockStarkRBACAuthorizationService](https://stark.nbb.be/api-docs/stark-rbac/latest/classes/MockStarkRBACAuthorizationService.html#readme)
```

The link would redirect directly on the README of the mocked class. 

What do you think @nicanac @christophercr ? 😊

**Comment by christophercr** [comment]
You're right... much better like that. I'll do the changes...

**Comment by christophercr** [comment]
@nicanac @SuperITMan done... I've applied the changes with the separate `.md` file for the "usage" as you suggested 😉

**Comment by SuperITMan** [comment]
@christophercr it seems perfect to me ! 😊 
Could you please squash your commits before we merge this ?

**Pull request merged**
