### PR TITLE
fix(unit-tests) include html files in karma-typescript config to support templateUrl syntax in components

### PR DESCRIPTION
**Pull request by christophercr**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Unit tests for components having a template defined with the templateUrl syntax are failing due to the HTML files not being included in the spec bundle created by karma-typescript. So as a workaround the `templateUrl: "some/path"` should be replaced by `template: require("some/path")`. 

Issue Number: #247 

## What is the new behavior?
Karma-typescript includes now the html files from the components, so the `templateUrl` syntax can be used in the components. The `template` syntax can still be used.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information
Some components were refactored to move their template to a separate .html file.

### CODE REVIEW

**Comment by SuperITMan** [comment]
It seems the command "npm run test" does not work anymore. Maybe shoulde we remote it ?
If we switch to karma-typescript, I think we could be able to remove the old way :)

**Comment by dsebastien** [comment]
@christophercr check out that commit: https://github.com/angular/angular/commit/b5be18f4059dc09ee9a3eb22ebd0b1485262e8fa

I don't know when we will be able to use this, but it should help

**Comment by christophercr** [comment]
Indeed, that feature will make things easier and faster ;)
In any case it is already working ;)

**Comment by christophercr** [comment]
@SuperITMan the "test" script still works, the problem is now that we have several TSLint violations due to the codelyzer rules :p

Any way, we can leave this script for now and remove it later on when we remove completely webpack for unit testing

**Pull request merged**
