### PR TITLE
feat(stark-ui): implement RestrictInput directive and module

### PR DESCRIPTION
**Pull request by christophercr**
ISSUES CLOSED: #546 #550 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #546 #550 

## What is the new behavior?
RestrictInput directive and module implemented

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by catlabs** [comment]
I created a ticket to add the directive to the showcase #550

**Comment by SuperITMan** [comment]
As @catlabs said, you forgot to add export the directive module in `packages/stark-ui/modules.ts`

**Comment by christophercr** [comment]
@SuperITMan @catlabs I've updated this PR, could you please review it?

**Comment by christophercr** [comment]
@SuperITMan I rebased my PR. Could you please have a look?

**Pull request merged**
