### PR TITLE
Feature/upgrade ngrx actions

### PR DESCRIPTION
**Pull request by SuperITMan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[X] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

ngrx actions are written in an old way.

Issue Number: #1340 #2551

## What is the new behavior?

Rewrite all Stark actions to comply new way of writing actions and effects.

## Does this PR introduce a breaking change?
```
[X] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by SuperITMan** [comment]
@christophercr @nicanac 
There are some things I'm not sure in this PR. Could you tell me what you think about:

1. I mentioned all the needed information about the breaking change in this commit message: https://github.com/NationalBankBelgium/stark/pull/2636/commits/ff836257e8ae94e69bc8f94ade47a9fa5c7dac9c
Should I do the same for other commits regarding stark-core and stark-ui or is it enough to have this information in the migration guide?

2. Before, the union types for actions was like `StarkErrorHandlingActions`. Now, it is like: `StarkErrorHandlingActions.ActionsTypes`. Do you think we could put `StarkErrorHandlingActions.Types` instead?

3. In the Migration Guide, I mentioned some regex expressions that can be used to update application code for the new actions style. Do you think it is relevant? If so, I add the same ones for stark-core and stark-rbac. Otherwise, I can remove them. Nevertheless, I think it would be awesome if we could provide a support for `ng update` in Stark 😃 

Thanks for your help!

**Comment by christophercr** [comment]
@SuperITMan nice job! Loads of boilerplate removed!! :rocket: 

About your questions, here are my suggestions:

1. I think the same information should be added to the other commits for Core and UI, specially because this is part of the Changelog, and the Migration Guide is a separate doc with much more info related to all changes and other stuff. So I would say that we stick to the good practice of providing nice info the in the changelogs :wink: 

2.  Indeed, I also agree that is better to have: `StarkErrorHandlingActions.Types`... is shorter and avoids duplication.

3. I think is a "nice detail" to give them the regex to quickly change the code. So I suggest to keep it. Of course an `ng update` would be better but... :man_shrugging:

**Review by christophercr — COMMENTED** [review]
Nice! I just left a comment above :point_up:

**Comment by SuperITMan** [comment]
Hey @christophercr 
I adapted the commits messages as we discussed to have a complete CHANGELOG.
I also changed `ActionsTypes` to `Types`. 

Thanks for your review 👍

**Comment by christophercr** [comment]
Mmm @SuperITMan just one little detail in the commit messages describing the breaking change, what do you think about re-phrasing it this way? Just to give more clarity :wink: 

```
BREAKING CHANGE:
Due to an improvement on how actions are defined, the enum `StarkRoutingActionsTypes` became obsolete so it has been removed.

As a result, the following actions have been changed:
- X
- Y
- Z

And also the previous union type has been replaced: `StarkRoutingActions` -> `StarkRoutingActions.Types`.
```

**Review by christophercr — COMMENTED** [review]
Mmm @SuperITMan just one little detail in the commit messages describing the breaking change, what do you think about re-phrasing it this way? Just to give more clarity :wink: 

```
BREAKING CHANGE:
Due to an improvement on how actions are defined, the enum `StarkRoutingActionsTypes` became obsolete so it has been removed.

As a result, the following actions have been changed:
- X
- Y
- Z

And also the previous union type has been replaced: `StarkRoutingActions` -> `StarkRoutingActions.Types`.
```

**Comment by SuperITMan** [comment]
Hi @christophercr 
Thanks for your suggestion, I'll have a look today to rephrase the commit messages 😊

**Comment by SuperITMan** [comment]
@christophercr @nicanac 

I updated this PR on your remark regarding the commit messages.
I also add a change for removal of "ngrx-store-freeze" thanks to @ngrx/store 8.x. 

Could you have a look ?

Thanks for your time! 😊

**Comment by nicanac** [comment]
> @christophercr @nicanac
> 
> I updated this PR on your remark regarding the commit messages.
> I also add a change for removal of "ngrx-store-freeze" thanks to @ngrx/store 8.x.
> 
> Could you have a look ?
> 
> Thanks for your time! 😊

I'm in to it now, I'll take the time to install your branch, because it's heavy duty work :-) 👍

**Review by nicanac — APPROVED** [review]
Indeed good work, it'll reduce the boilerplate.
👍

**Review by christophercr — APPROVED** [review]
Awesome! :+1: :+1:

**Pull request merged**
